version: '3.8'

services:
 blanball-fe-prod:
  container_name: blanball-fe-prod
  volumes:
    - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
  build:
   context: .
   dockerfile: Dockerfile
  command: 'bash build.sh'
  ports:
   - "49211:49211"